package com.nj.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nj.Bean.ReUploadBean;
import com.nj.Bean.UserBean;

import com.nj.greendao.ReUploadBeanDao;
import com.nj.greendao.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reUploadBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final ReUploadBeanDao reUploadBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reUploadBeanDaoConfig = daoConfigMap.get(ReUploadBeanDao.class).clone();
        reUploadBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        reUploadBeanDao = new ReUploadBeanDao(reUploadBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(ReUploadBean.class, reUploadBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        reUploadBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public ReUploadBeanDao getReUploadBeanDao() {
        return reUploadBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
